# Generated by Django 5.2.7 on 2025-10-15 14:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('weight', 'Weight Loss/Gain'), ('steps', 'Daily Steps'), ('exercise', 'Exercise Duration'), ('sleep', 'Sleep Hours'), ('water', 'Water Intake')], max_length=20)),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField(default=0)),
                ('deadline', models.DateField()),
                ('is_achieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('nutrition', 'Nutrition'), ('exercise', 'Exercise'), ('sleep', 'Sleep'), ('lifestyle', 'Lifestyle')], max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)])),
                ('height', models.FloatField(help_text='Height in cm', validators=[django.core.validators.MinValueValidator(50)])),
                ('weight', models.FloatField(help_text='Weight in kg', validators=[django.core.validators.MinValueValidator(20)])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Lightly Active'), ('moderate', 'Moderately Active'), ('very', 'Very Active'), ('extra', 'Extra Active')], default='moderate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('calories_intake', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('protein', models.FloatField(help_text='Grams', validators=[django.core.validators.MinValueValidator(0)])),
                ('carbs', models.FloatField(help_text='Grams', validators=[django.core.validators.MinValueValidator(0)])),
                ('fats', models.FloatField(help_text='Grams', validators=[django.core.validators.MinValueValidator(0)])),
                ('water_intake', models.FloatField(help_text='Liters', validators=[django.core.validators.MinValueValidator(0)])),
                ('steps', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('exercise_duration', models.IntegerField(help_text='Minutes', validators=[django.core.validators.MinValueValidator(0)])),
                ('exercise_type', models.CharField(blank=True, max_length=100)),
                ('sleep_hours', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('heart_rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(220)])),
                ('blood_pressure_sys', models.IntegerField(blank=True, help_text='Systolic', null=True)),
                ('blood_pressure_dia', models.IntegerField(blank=True, help_text='Diastolic', null=True)),
                ('mood', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('okay', 'Okay'), ('bad', 'Bad'), ('terrible', 'Terrible')], default='okay', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
