# Generated by Django 5.2.7 on 2025-10-19 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeapp', '0002_nutritionentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='target_weight',
            field=models.FloatField(blank=True, help_text='Target weight in kg', null=True, validators=[django.core.validators.MinValueValidator(20)]),
        ),
    ]
